const doctors = [
  {
    name: "Dr. Rahul Sharma",
    email: "rahul1@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Cardiologist",
    degree: "MBBS, MD",
    experience: "5 Years",
    about: "Heart specialist with 5 years experience.",
    available: true,
    fees: 500,
    address: { line1: "MG Road", line2: "Delhi" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Priya Patel",
    email: "priya2@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Dermatologist",
    degree: "MBBS, MD",
    experience: "3 Years",
    about: "Skin care expert.",
    available: true,
    fees: 400,
    address: { line1: "Satellite", line2: "Ahmedabad" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Amit Verma",
    email: "amit3@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Orthopedic",
    degree: "MBBS, MS",
    experience: "7 Years",
    about: "Bone and joint specialist.",
    available: true,
    fees: 600,
    address: { line1: "Andheri", line2: "Mumbai" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Sneha Gupta",
    email: "sneha4@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Pediatrician",
    degree: "MBBS, MD",
    experience: "4 Years",
    about: "Child health expert.",
    available: true,
    fees: 450,
    address: { line1: "Noida", line2: "UP" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Raj Mehta",
    email: "raj5@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Neurologist",
    degree: "MBBS, DM",
    experience: "8 Years",
    about: "Brain and nerve specialist.",
    available: true,
    fees: 800,
    address: { line1: "SG Highway", line2: "Ahmedabad" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Kavita Singh",
    email: "kavita6@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Gynecologist",
    degree: "MBBS, MS",
    experience: "6 Years",
    about: "Women health expert.",
    available: true,
    fees: 550,
    address: { line1: "Bhopal", line2: "MP" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Arjun Reddy",
    email: "arjun7@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "ENT Specialist",
    degree: "MBBS, MS",
    experience: "5 Years",
    about: "Ear, nose, throat specialist.",
    available: true,
    fees: 400,
    address: { line1: "Hyderabad", line2: "Telangana" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Neha Jain",
    email: "neha8@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Dentist",
    degree: "BDS, MDS",
    experience: "4 Years",
    about: "Dental care expert.",
    available: true,
    fees: 300,
    address: { line1: "Indore", line2: "MP" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Vikram Desai",
    email: "vikram9@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Psychiatrist",
    degree: "MBBS, MD",
    experience: "9 Years",
    about: "Mental health specialist.",
    available: true,
    fees: 700,
    address: { line1: "Pune", line2: "Maharashtra" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Pooja Shah",
    email: "pooja10@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Ophthalmologist",
    degree: "MBBS, MS",
    experience: "6 Years",
    about: "Eye specialist.",
    available: true,
    fees: 500,
    address: { line1: "Surat", line2: "Gujarat" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Rohan Kapoor",
    email: "rohan11@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "General Physician",
    degree: "MBBS",
    experience: "3 Years",
    about: "General health care doctor.",
    available: true,
    fees: 300,
    address: { line1: "Chandigarh", line2: "Punjab" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Anjali Verma",
    email: "anjali12@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Endocrinologist",
    degree: "MBBS, MD",
    experience: "7 Years",
    about: "Hormone specialist.",
    available: true,
    fees: 650,
    address: { line1: "Lucknow", line2: "UP" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Karan Malhotra",
    email: "karan13@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Urologist",
    degree: "MBBS, MS",
    experience: "8 Years",
    about: "Urinary system specialist.",
    available: true,
    fees: 700,
    address: { line1: "Jaipur", line2: "Rajasthan" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Meera Nair",
    email: "meera14@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Oncologist",
    degree: "MBBS, MD",
    experience: "10 Years",
    about: "Cancer specialist.",
    available: true,
    fees: 900,
    address: { line1: "Kochi", line2: "Kerala" },
    date: Date.now(),
    slots_booked: {}
  },
  {
    name: "Dr. Suresh Iyer",
    email: "suresh15@gmail.com",
    password: "123456",
    image: "https://via.placeholder.com/150",
    speciality: "Pulmonologist",
    degree: "MBBS, MD",
    experience: "6 Years",
    about: "Lung specialist.",
    available: true,
    fees: 550,
    address: { line1: "Chennai", line2: "Tamil Nadu" },
    date: Date.now(),
    slots_booked: {}
  }
];

export default doctors;